### ISSUE TITLE
Crash during "Checking for stale beam files"

### ISSUE THREAD

**Issue by pgrunwald** [JakeBecker/elixir-ls#100]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 20 [erts-9.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.5 (compiled with OTP 19)
```

* Operating system: Mac OS 10.13.6

* Client (editor or IDE): VS Code 1.25.1

### Crash details

Elixir LS crashes when I open my project in VS Code. This behavior started suddenly without changing any settings. It seems that the issue is that the `update_stale` task is taking longer than 5000ms, but that's just from a quick look at that output.

```Started ElixirLS

Compiling with Mix env test

[Info  - 11:14:39] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 11:14:39] [ElixirLS Dialyzer] Analysis finished in 118 milliseconds
[Info  - 11:14:42] [ElixirLS Dialyzer] Writing manifest...
[Info  - 11:14:46] [ElixirLS Dialyzer] Done writing manifest.
[Info  - 11:14:47] Compile took 7799 milliseconds
[Info  - 11:14:47] [ElixirLS Dialyzer] Checking for stale beam files
[Error - 11:14:53] GenServer {#PID<0.100.0>, ElixirLS.LanguageServer.Dialyzer} terminating
** (stop) exited in: Task.Supervised.stream(5000)
    ** (EXIT) time out
    (elixir) lib/task/supervised.ex:269: Task.Supervised.stream_reduce/7
    (elixir) lib/enum.ex:1919: Enum.reverse/1
    (elixir) lib/enum.ex:2588: Enum.to_list/1
    (elixir) lib/enum.ex:1163: Enum.into/2
    (language_server) lib/language_server/dialyzer.ex:216: ElixirLS.LanguageServer.Dialyzer.update_stale/4
    (language_server) lib/language_server/dialyzer.ex:130: ElixirLS.LanguageServer.Dialyzer.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
Last message (from ElixirLS.LanguageServer.Server): {:analyze, []}
[Error - 11:14:53] Process #PID<0.103.0> terminating
** (exit) exited in: Task.Supervised.stream(5000)
    ** (EXIT) time out
    (elixir) lib/task/supervised.ex:269: Task.Supervised.stream_reduce/7
    (elixir) lib/enum.ex:1919: Enum.reverse/1
    (elixir) lib/enum.ex:2588: Enum.to_list/1
    (elixir) lib/enum.ex:1163: Enum.into/2
    (language_server) lib/language_server/dialyzer.ex:216: ElixirLS.LanguageServer.Dialyzer.update_stale/4
    (language_server) lib/language_server/dialyzer.ex:130: ElixirLS.LanguageServer.Dialyzer.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
Initial Call: ElixirLS.LanguageServer.Dialyzer.init/1
Ancestors: [#PID<0.102.0>, ElixirLS.LanguageServer.Server, ElixirLS.LanguageServer.Supervisor, #PID<0.98.0>]
Neighbours:
    #PID<0.492.0>
        Initial Call: :erlang.apply/2
        Current Call: Task.Supervised.stream_monitor_loop/2
        Ancestors: []
[Error - 11:14:53] GenServer ElixirLS.LanguageServer.Server terminating
** (stop) exited in: GenServer.call({:global, {#PID<0.100.0>, ElixirLS.LanguageServer.Dialyzer}}, {:analyze, []}, :infinity)
    ** (EXIT) exited in: Task.Supervised.stream(5000)
        ** (EXIT) time out
    (elixir) lib/gen_server.ex:836: GenServer.call/3
    (language_server) lib/language_server/server.ex:479: ElixirLS.LanguageServer.Server.dialyze/1
    (language_server) lib/language_server/server.ex:496: ElixirLS.LanguageServer.Server.handle_build_result/3
    (language_server) lib/language_server/server.ex:99: ElixirLS.LanguageServer.Server.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:build_finished, {:noop, []}}}
[Error - 11:14:53] Process ElixirLS.LanguageServer.Server (#PID<0.100.0>) terminating
** (exit) exited in: GenServer.call({:global, {#PID<0.100.0>, ElixirLS.LanguageServer.Dialyzer}}, {:analyze, []}, :infinity)
    ** (EXIT) exited in: Task.Supervised.stream(5000)
        ** (EXIT) time out
    (elixir) lib/gen_server.ex:836: GenServer.call/3
    (language_server) lib/language_server/server.ex:479: ElixirLS.LanguageServer.Server.dialyze/1
    (language_server) lib/language_server/server.ex:496: ElixirLS.LanguageServer.Server.handle_build_result/3
    (language_server) lib/language_server/server.ex:99: ElixirLS.LanguageServer.Server.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Initial Call: ElixirLS.LanguageServer.Server.init/1
Ancestors: [ElixirLS.LanguageServer.Supervisor, #PID<0.98.0>]
[Error - 11:14:53] Child ElixirLS.LanguageServer.Dialyzer of Supervisor #PID<0.102.0> (ElixirLS.LanguageServer.Dialyzer.Supervisor) terminated
** (exit) exited in: Task.Supervised.stream(5000)
    ** (EXIT) time out
Pid: #PID<0.103.0>
Start Call: ElixirLS.LanguageServer.Dialyzer.start_link({#PID<0.100.0>, "/Users/percy/Code/mindoula-server-elixir"})
[Error - 11:14:53] Child ElixirLS.LanguageServer.Server of Supervisor ElixirLS.LanguageServer.Supervisor terminated
** (exit) exited in: GenServer.call({:global, {#PID<0.100.0>, ElixirLS.LanguageServer.Dialyzer}}, {:analyze, []}, :infinity)
    ** (EXIT) exited in: Task.Supervised.stream(5000)
        ** (EXIT) time out
Pid: #PID<0.100.0>
Start Call: ElixirLS.LanguageServer.Server.start_link(ElixirLS.LanguageServer.Server)
[Error - 11:14:53] Child ElixirLS.LanguageServer.Server of Supervisor ElixirLS.LanguageServer.Supervisor caused shutdown
** (exit) :reached_max_restart_intensity
Start Call: ElixirLS.LanguageServer.Server.start_link(ElixirLS.LanguageServer.Server)
```

**Comment by Ablu** [comment]
thanks for the fix! Is there any chance this will land in a release of the VSCode extension anytime soon? :blush:
