### ISSUE TITLE
DocumentSymbols.list_symbols does not handle compilation errors gracefully

### ISSUE THREAD

**Issue by lukaszsamson** [JakeBecker/elixir-ls#107]
### Environment

* Elixir & Erlang versions (elixir --version):
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.1 (compiled with Erlang/OTP 21)
* Operating system: OSX 10.13.6
* Client (editor or IDE): 1.25.1
* Plugin: 0.2.22

### Crash report template

When editing `.ex` and there is a compile error files the log is cluttered with errors such as - the server keeps crashing and restarting

```
[Error - 09:47:59] Request textDocument/documentSymbol failed.
  Message: an exception was raised:
    ** (SyntaxError) nofile:48: syntax error before: where
        (language_server) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
        (language_server) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
        (language_server) lib/language_server/server.ex:403: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000 

09:47:59.983 [error] Process #PID<0.10040.2> raised an exception
** (SyntaxError) nofile:48: syntax error before: where
    (language_server) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
    (language_server) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
    (language_server) lib/language_server/server.ex:403: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2

[Error - 09:48:01] Request textDocument/documentSymbol failed.
  Message: an exception was raised:
    ** (SyntaxError) nofile:48: syntax error before: where
        (language_server) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
        (language_server) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
        (language_server) lib/language_server/server.ex:403: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000 
```

**Comment by lukaszsamson** [comment]
The problem here is the crashing process keeps getting restarted just to crash again burning cpu cycles. Maybe vscode retries `textDocument/documentSymbol` requests when the response is `:server_error`.
As for "let it crash", IMO it should not be applied to expected errors. And compilation error in code editor is the expected one.

**Comment by JakeBecker** [comment]
The new Outline view in VS Code refreshes the document symbol list after every change to the document, so these errors would tend to happen frequently. For the error response, `:server_error` seems more appropriate than `:parse_error` since according to the JSON RPC spec, that indicates that invalid JSON was received by the server: https://www.jsonrpc.org/specification#error_object .  Since the client would end up getting an error anyway, I prefer not to handle it explicitly.
