### ISSUE TITLE
Couldn't start client ElixirLS

### ISSUE THREAD

**Issue by mister11** [JakeBecker/elixir-ls#111]
### Environment

* Elixir & Erlang versions (elixir --version):

Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] (installed from .deb file downloaded from erlang solutions web page)

Elixir 1.7.1 (compiled with Erlang/OTP 21) (installed using kiex, added to PATH)

* Operating system: Linux Mint 19 (Tara)
* Client (editor or IDE): Visual Studio Code

Hi Jake!

I'm getting an error: Couldn't start client ElixirLS.

I've done same thing you've proposed in other issue which is to download zip (latest available was 0.2.19) and run `language_server.sh` and there was no error.

From what I can see in JS console, it crashes in `vscode-languageclient` `npm` module which might be some error unrelated to this project, but VS itself. Nevertheless, I'll c/p issue since it might be useful.

```
Couldn't start client ElixirLS  in   e.onDidNotificationChange @ notificationsAlerts.ts:42

[JakeBecker.elixir-ls]spawn EACCES in mainThreadExtensionService.ts:43

Error: spawn EACCES
	at exports._errnoException (util.js:1050:11)
	at ChildProcess.spawn (internal/child_process.js:319:11)
	at Object.exports.spawn (child_process.js:390:9)
	at _getServerWorkingDir.then.serverWorkingDir (/home/mister11/.vscode/extensions/JakeBecker.elixir-ls-0.2.22/node_modules/vscode-languageclient/lib/main.js:347:40)
	at <anonymous>   in mainThreadExtensionService.ts:44
```

**Comment by mister11** [comment]
Thank you, that helped 😄
