### ISSUE TITLE
Crashes repeatedly with a certain project

### ISSUE THREAD

**Issue by x-ji** [JakeBecker/elixir-ls#138]
### Environment

* Elixir & Erlang versions (elixir --version):

```
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
```

* Operating system: Arch/Manjaro Linux 4.19.4-1-MANJARO
* Client (editor or IDE): VSCode 1.29.1

Output from the plugin:

```
Started ElixirLS
Elixir version: "1.7.3 (compiled with Erlang/OTP 21)"
Erlang version: "21"
Compiling with Mix env test
[Info  - 9:13:50 PM] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 9:13:50 PM] [ElixirLS Dialyzer] Analysis finished in 99 milliseconds
init terminating in do_boot ({badarg,[{io,put_chars,[standard_error,unicode,[_]],[]},{Elixir.Kernel.CLI,exec_fun,2,[{_},{_}]},{Elixir.Kernel.CLI,run,2,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[

Crash dump is being written to: erl_crash.dump...done
[Info  - 9:13:54 PM] Connection to server got closed. Server will restart.
[Error - 9:13:54 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/main.js:825:25)
    at Object.dispose (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-languageclient/lib/client.js:57:35)
    at LanguageClient.handleConnectionClosed (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-languageclient/lib/client.js:2036:42)
    at LanguageClient.handleConnectionClosed (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-languageclient/lib/main.js:127:15)
    at closeHandler (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-languageclient/lib/client.js:2023:18)
    at CallbackList.invoke (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at closeHandler (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/main.js:221:26)
    at CallbackList.invoke (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at StreamMessageWriter.AbstractMessageWriter.fireClose (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/messageWriter.js:57:27)
    at Socket.<anonymous> (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/messageWriter.js:79:63)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
[Error - 9:13:54 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/main.js:825:25)
    at Object.dispose (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-languageclient/lib/client.js:57:35)
    at LanguageClient.handleConnectionClosed (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-languageclient/lib/client.js:2036:42)
    at LanguageClient.handleConnectionClosed (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-languageclient/lib/main.js:127:15)
    at closeHandler (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-languageclient/lib/client.js:2023:18)
    at CallbackList.invoke (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at closeHandler (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/main.js:221:26)
    at CallbackList.invoke (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at StreamMessageWriter.AbstractMessageWriter.fireClose (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/messageWriter.js:57:27)
    at Socket.<anonymous> (/home/jx/.vscode/extensions/jakebecker.elixir-ls-0.2.24/node_modules/vscode-jsonrpc/lib/messageWriter.js:79:63)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

The above output just repeats itself until VSCode decide to not restart the language server.

Strangely this only happens for one of my projects so it seems to be something specific to that. But I have no idea what it can be exactly.

I can compile the project in the command line fine.

**Comment by lesha1201** [comment]
I have the same problem but deleting the `.elixirls` and `_build` doesn't help. I think this is because I have problems with compiling `argon2_elixir` on Windows 10. I can compile it only when I run cmd with proper environments set, e.g. `cmd /K "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64`. And ElixirLS throws an error on compilation of `argon2_elixir`

Output:
```
Started ElixirLS
Elixir version: "1.8.1 (compiled with Erlang/OTP 20)"
Erlang version: "21"
Compiling with Mix env test
==> argon2_elixir

init terminating in do_boot ({badarg,[{io,put_chars,[standard_error,unicode,[_]],[]},{Elixir.Kernel.CLI,exec_fun,2,[{_},{_}]},{Elixir.Kernel.CLI,run,2,[{_},{_}]},{init,start_em,1,[{_},{_}]},{init,do_b

Crash dump is being written to: erl_crash.dump...done
[Error - 18:25:08] Connection to server got closed. Server will not be restarted.
[Error - 18:25:08] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-languageclient\lib\client.js:2036:42)
	at LanguageClient.handleConnectionClosed (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-languageclient\lib\main.js:127:15)
	at closeHandler (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-languageclient\lib\client.js:2023:18)
	at CallbackList.invoke (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at Socket.<anonymous> (C:\Users\lesha\.vscode\extensions\jakebecker.elixir-ls-0.2.24\node_modules\vscode-jsonrpc\lib\messageReader.js:188:62)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
```

OS: `Windows 10 Pro 1809`

Deps:
```
[
      {:phoenix, "~> 1.4.2"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto_sql, "~> 3.0"},
      {:postgrex, ">= 0.0.0"},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:argon2_elixir, "~> 2.0"},
      {:absinthe, "~> 1.4"},
      {:absinthe_phoenix, "~> 1.4"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe_ecto, "~> 0.1.3"}
]
```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
