### ISSUE TITLE
Compilation error in file lib/language_server/dialyzer/analyzer.ex

### ISSUE THREAD

**Issue by 0rzech** [JakeBecker/elixir-ls#174]
### Environment

* Elixir & Erlang versions (elixir --version): `Elixir 1.8.2` @ `Erlang/OTP 20`
* Operating system: `Ubuntu 18.04.2`

### Problem Description

elixir-ls compilation (`mix compile`) on master and latest release fails with:
```
== Compilation error in file lib/language_server/dialyzer/analyzer.ex ==
** (RuntimeError) error parsing file /usr/lib/erlang/lib/dialyzer-3.2.3/src/dialyzer.hrl, got: {:error, :enoent}
    (elixir) lib/record/extractor.ex:84: Record.Extractor.read_file/2
    (elixir) lib/record/extractor.ex:50: Record.Extractor.extract_record/2
    lib/language_server/dialyzer/analyzer.ex:42: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by 0rzech** [comment]
The solution is to install `erlang-src` package in Ubuntu.
