### ISSUE TITLE
ets.lookup_element error in project with broken elixir module

### ISSUE THREAD

**Issue by balduncle** [JakeBecker/elixir-ls#33]
I'm using the latest ide-elixir from git (0c478c) in Atom.  When code in `MyModule` is broken and won't compile, I get the following error when viewing `mix.exs` for my project, and every line of `mix.exs` is underlined with a red dashed line.

```
an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.lookup_element(:elixir_modules, MyModule, 2)
        (elixir) src/elixir_module.erl:27: :elixir_module.data_table/1
        (elixir) lib/kernel/lexical_tracker.ex:37: Kernel.LexicalTracker.to_pid/1
        (elixir) lib/kernel/lexical_tracker.ex:16: Kernel.LexicalTracker.remote_references/1
        (mix) lib/mix/compilers/elixir.ex:216: Mix.Compilers.Elixir.each_module/4
        (elixir) lib/kernel/parallel_compiler.ex:293: Kernel.ParallelCompiler.wait_for_messages/6
        (elixir) lib/kernel/parallel_compiler.ex:129: Kernel.ParallelCompiler.spawn_workers/3
        (mix) lib/mix/compilers/elixir.ex:166: Mix.Compilers.Elixir.compile_manifest/9
```

I assume this should be reported here instead of at ide-elixir, but let me know if I should adjust.  Thanks.

**Comment by balduncle** [comment]
I initially submitted this issue here thinking elixir-ls was using ETS behind the scenes, but I see now this is just the normal compiler error being displayed in the context of `mix.exs`.  So I'm guessing this issue should really be a UI/UX issue for ide-elixir.
