### ISSUE TITLE
bugreport: Errors not going away after fixing them

### ISSUE THREAD

**Issue by DuffmanBE** [JakeBecker/elixir-ls#36]
Hi, 

I absolutely love this plug-in but I encountered a bug (which is not occurring on my colleague's machine). Whenever the tool (rightfully) tells me there's an error in my code, the Error Message is not removed from the list of warnings & errors after fixing it. I have to restart Visual Studio Code in order to get rid of the message. 
[I uploaded a video of 30 seconds which shows the bug](https://youtu.be/Ej-Terk_ffg). The video shows that ElixlrLS lists an error after I write faulty code. After removing the faulty code, it is shown that the error remains in the list. After restarting VS Code, it is shown that the error is no longer there.

Kind regards

**Comment by JakeBecker** [comment]
Can you paste the contents of the "Output" pane (with ElixirLS selected in its dropdown)? That's where errors and other logs will show up and it's helpful for debugging it.

**Comment by DuffmanBE** [comment]
Hi Jake,

Thanks for getting back to me.
This is what the output looks like after writing the erroneous code + saving:
`Compiling with Mix env test

[Info  - 12:58:41] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 12:58:41] [ElixirLS Dialyzer] Analysis finished in 55 milliseconds
[Info  - 12:58:41] Compile took 114 milliseconds
[Info  - 12:58:41] [ElixirLS Dialyzer] Writing manifest...
[Info  - 12:58:41] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 12:58:42] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 12:58:42] [ElixirLS Dialyzer] Analysis finished in 46 milliseconds
[Info  - 12:58:42] [ElixirLS Dialyzer] Writing manifest...
[Info  - 12:58:44] [ElixirLS Dialyzer] Done writing manifest.
Compiling with Mix env test

Compiling 1 file (.ex)


== Compilation error in file lib/node/beta_node.ex ==
** (ArgumentError) cannot invoke def/2 outside module
    (elixir) lib/kernel.ex:5090: Kernel.assert_module_scope/3
    (elixir) lib/kernel.ex:3884: Kernel.define/4
    (elixir) expanding macro: Kernel.def/2
    lib/node/beta_node.ex:223: (file)

[Info  - 12:59:13] Compile took 59 milliseconds
`

And this is what the output looks like after removing the erroneous code and saving (but still showing the error like I described above)
`Compiling with Mix env test

[Info  - 12:58:41] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 12:58:41] [ElixirLS Dialyzer] Analysis finished in 55 milliseconds
[Info  - 12:58:41] Compile took 114 milliseconds
[Info  - 12:58:41] [ElixirLS Dialyzer] Writing manifest...
[Info  - 12:58:41] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 12:58:42] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 12:58:42] [ElixirLS Dialyzer] Analysis finished in 46 milliseconds
[Info  - 12:58:42] [ElixirLS Dialyzer] Writing manifest...
[Info  - 12:58:44] [ElixirLS Dialyzer] Done writing manifest.
Compiling with Mix env test

Compiling 1 file (.ex)


== Compilation error in file lib/node/beta_node.ex ==
** (ArgumentError) cannot invoke def/2 outside module
    (elixir) lib/kernel.ex:5090: Kernel.assert_module_scope/3
    (elixir) lib/kernel.ex:3884: Kernel.define/4
    (elixir) expanding macro: Kernel.def/2
    lib/node/beta_node.ex:223: (file)

[Info  - 12:59:13] Compile took 59 milliseconds
Compiling with Mix env test

Compiling 1 file (.ex)

[Warn  - 13:00:40] warning: code block contains unused literal "depending on whether has_changed/state.retraction_matched evaluates to true, \nthe value of i that is passed along to retract_successor should be different.\nif the retraction from the right passes it should be 0. \nIf the retraction from the left passes it should be incremented by 1.\n" (remove the literal or assign it to _ to avoid warnings)
  lib/node/beta_node.ex


[Warn  - 13:00:40] warning: clauses for the same def should be grouped together, def handle_cast/2 was previously defined (lib/node/beta_node.ex:25)
  lib/node/beta_node.ex:46


[Warn  - 13:00:40] warning: clauses for the same def should be grouped together, def handle_cast/2 was previously defined (lib/node/beta_node.ex:64)
  lib/node/beta_node.ex:104


[Warn  - 13:00:40] warning: code block contains unused literal "Tokens match!(beta)" (remove the literal or assign it to _ to avoid warnings)
  lib/node/beta_node.ex:171


[Warn  - 13:00:40] warning: variable "has_changed_previously" is unused
  lib/node/beta_node.ex:104


[Warn  - 13:00:40] warning: variable "has_changed_previously" is unused
  lib/node/beta_node.ex:108


[Warn  - 13:00:40] warning: variable "succ_pid" is unused
  lib/node/beta_node.ex:141


[Warn  - 13:00:40] warning: variable "succ_pid" is unused
  lib/node/beta_node.ex:147


[Warn  - 13:00:40] warning: variable "token" is unused
  lib/node/beta_node.ex:167


[Warn  - 13:00:40] warning: variable "has_changed" is unused
  lib/node/beta_node.ex:189


[Warn  - 13:00:40] warning: variable "fact" is unused
  lib/node/beta_node.ex:199


[Warn  - 13:00:40] warning: variable "name" is unused
  lib/node/beta_node.ex:199


[Warn  - 13:00:40] warning: variable "has_changed" is unused
  lib/node/beta_node.ex:208


[Warn  - 13:00:40] warning: variable "i" is unused
  lib/node/beta_node.ex:218


[Warn  - 13:00:40] warning: variable "wme" is unused
  lib/node/beta_node.ex:218


[Warn  - 13:00:40] warning: function Node.BetaNode.start_link/3 is undefined or private. Did you mean one of:

      * start_link/4

  lib/play_ground.ex:12


[Info  - 13:00:40] Compile took 168 milliseconds
[Info  - 13:00:40] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 13:00:40] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 13:00:40] [ElixirLS Dialyzer] Analysis finished in 21 milliseconds
[Info  - 13:00:40] [ElixirLS Dialyzer] Writing manifest...
[Info  - 13:00:42] [ElixirLS Dialyzer] Done writing manifest.
`
Sorry for the many warnings in my code. I will take care of them soon!

**Comment by JakeBecker** [comment]
Closing due to inactivity.
