### ISSUE TITLE
Correctly debugging application code

### ISSUE THREAD

**Issue by micahrye** [JakeBecker/elixir-ls#39]
I found your Elixir-LS project and vscode and really like them together. I am able to set breakpoints in "tests" but not in my app. I am not sure how to correctly create a configuration. Here is the (default) test config that works: 
```
{
      "type": "mix_task",
      "name": "mix test",
      "request": "launch",
      "task": "test",
      "taskArgs": [
        "--trace"
      ],
      "startApps": true,
      "projectDir": "${workspaceRoot}",
      "requireFiles": [
        "test/**/test_helper.exs",
        "test/**/*_test.exs"
      ]
    }
```

If I "add" a new configuration from vscode: 
```
{
      "type": "mix_task",
      "request": "launch",
      "name": "mix task",
      "task": "task",
      "taskArgs": [],
      "projectDir": "${workspaceRoot}"
    }
```
and try to run it it results in the following: 
```
(Debugger) Task failed because an exception was raised:
    ** (Mix.NoTaskError) The task "task" could not be found
        (mix) lib/mix/task.ex:234: Mix.Task.get!/1
        (mix) lib/mix/task.ex:297: Mix.Task.run_task/3
```

I have played around with the config, trying to copy from the test config that works without success. And it was not clear to me from the README.md how to config them. 

I am not sure if I am required to do the steps in the "Building and running" section of the README.md, but when I try running `mix release -o <release_dir>` I get the following error: `** (Mix) The task "release" could not be found`

Clarification appreciated.

**Comment by micahrye** [comment]
I was able to get breakpoints working correctly in my project by coping the config info [here](https://github.com/JakeBecker/elixir-ls/blob/9d0af2c785c14d69f912cf093f93573d8127dd19/apps/debugger/test/fixtures/mix_project/.vscode/launch.json)

Not sure if I had deleted the "mix (Default task)" object 
```
{
      "type": "mix_task",
      "name": "mix (Default task)",
      "request": "launch",
      "projectDir": "${workspaceRoot}"
}
```
when I first was exploring it in vscode. I do know when you "Add Configuration..."  it adds the following object: 
```
{
      "type": "mix_task",
      "request": "launch",
      "name": "mix task",
      "task": "task",
      "taskArgs": [],
      "projectDir": "${workspaceRoot}"
}
```

Which has a similar shape to the "test" configuration
```
{
      "type": "mix_task",
      "name": "mix test",
      "request": "launch",
      "task": "test",
      "taskArgs": [
        "--trace"
      ],
      "startApps": true,
      "projectDir": "${workspaceRoot}",
      "requireFiles": [
        "test/**/test_helper.exs",
        "test/**/*_test.exs"
      ]
    }
```
that did work, and led me in the wrong direction. 

Documentation that explains the configuration would be helpful. 

Here is my take based on [vscode docs](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations): 
* `type` - the type of debugger to use for this launch configuration. In the case of ElixirLS the `type` must be `mix_task`
* `name` -  friendly name which appears in the Debug launch configuration dropdown
* `request` - the request type of this launch configuration. Currently supported are launch and attach. I believe ElixirLS only supports `launch`.
* `projectDir` - is a variable set with the vscode defined `workspaceRoot`. [${workspaceRoot} is defined by VS Code itself. This is the folder you opened when you used "Open Folder" option in "File"] (https://github.com/Microsoft/vscode-cpptools/issues/1104). `projectDir` is used by ElixirLS `ElixirLS.Debugger.Server. initialize`

This is a very nice project overall, thanks.
