### ISSUE TITLE
Do not complete with current project files

### ISSUE THREAD

**Issue by hauleth** [JakeBecker/elixir-ls#40]
I am using NeoVim with vim-lsp and ElixirLS and all completions available are ones in the standard library.

I am running my server using:

    env ERL_LIBS=$ERL_LIBS:$HOME/Workspace/JakeBecker/elixir-ls/lsp mix elixir_ls.language_server

Completion for stdlib works fine, but I have no completion for either my code nor any of the dependencies. All I get is completion for module defined in mixfile.

**Comment by JakeBecker** [comment]
The autocompletion relies on your beam files being built successfully, so it's likely that the build is failing or being skipped for some reason.

Are you using Windows? If so, it's likely caused by this: https://github.com/JakeBecker/elixir-ls/pull/43 .  I'll be doing a release sometime this weekend with that fix, so hopefully that'll solve the problem if it's a Windows issue.

If you're not using Windows, I'll need to look into it more. Does the NeoVim client let you see the log messages from the server? Those are really helpful for diagnosing issues like this, but unfortunately some clients don't show them.

**Comment by hauleth** [comment]
1. Build via `mix compile` passes perfectly, but when I check logs ElixirLS almost always say that it couldn't compile file due to missing `use`d modules (like `Ecto.Schema`):
```
sob 13 sty 22:20:52 2018:["--->", 3, "elixir-ls", {"method": "textDocument/completion", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex"}, "position": {"character": 7, "line": 27}}}]
sob 13 sty 22:20:52 2018:["<---", 3, "elixir-ls", {"response": {"id": 2, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Internal error: an exception was raised:\n    ** (CompileError) /Users/hauleth/Workspace/JakeBecker/elixir-ls/deps/elixir_sense/lib/elixir_sense/core/ast.ex:19: module Kokon.Schema is not loaded and could not be found\n        (elixir) src/elixir_expand.erl:86: :elixir_expand.expand/2\n        (elixir) src/elixir_expand.erl:489: :elixir_expand.expand_block/4\n        (elixir) src/elixir_expand.erl:39: :elixir_expand.expand/2\n        (elixir) src/elixir.erl:265: :elixir.quoted_to_erl/3\n        (elixir) src/elixir.erl:224: :elixir.eval_forms/4\n        (elixir) lib/code.ex:186: Code.eval_string/3\n        (elixir_sense) lib/elixir_sense/core/ast.ex:66: ElixirSense.Core.Ast.add_directive_modules_to_env/3"}}, "request": {"method": "textDocument/completion", "jsonrpc": "2.0", "id": 2, "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex"}, "position": {"character": 7, "line": 27}}}}]
sob 13 sty 22:20:52 2018:["<---", 3, "elixir-ls", {"response": {"method": "window/logMessage", "jsonrpc": "2.0", "params": {"message": "Process #PID<0.109.0> raised an exception\n** (CompileError) /Users/hauleth/Workspace/JakeBecker/elixir-ls/deps/elixir_sense/lib/elixir_sense/core/ast.ex:19: module Kokon.Schema is not loaded and could not be found\n    (elixir) src/elixir_expand.erl:86: :elixir_expand.expand/2\n    (elixir) src/elixir_expand.erl:489: :elixir_expand.expand_block/4\n    (elixir) src/elixir_expand.erl:39: :elixir_expand.expand/2\n    (elixir) src/elixir.erl:265: :elixir.quoted_to_erl/3\n    (elixir) src/elixir.erl:224: :elixir.eval_forms/4\n    (elixir) lib/code.ex:186: Code.eval_string/3\n    (elixir_sense) lib/elixir_sense/core/ast.ex:66: ElixirSense.Core.Ast.add_directive_modules_to_env/3", "type": 1}}}]
```
2. No I am using macOS (`Darwin niuniobook 16.7.0 Darwin Kernel Version 16.7.0: Tue Dec 19 10:16:45 PST 2017; root:xnu-3789.73.5~1/RELEASE_X86_64 x86_64`) with Elixir 1.6.0-rc.1:
```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.0-rc.1 (67e575e) (compiled with OTP 19)
```

**Comment by hauleth** [comment]
Whole log:

```
ndz 14 sty 14:28:25 2018:["s:on_text_document_did_open()", 1, "elixir", "/Users/hauleth/Workspace/getkokon/api", "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex"]
ndz 14 sty 14:28:25 2018:[{"response": {"data": {"__data__": "vim-lsp", "lsp_id": 2, "server_name": "elixir-ls"}, "message": "started lsp server successfully"}}]
ndz 14 sty 14:28:25 2018:["--->", 2, "elixir-ls", {"method": "initialize", "params": {"rootUri": "file:///Users/hauleth/Workspace/getkokon/api", "initializationOptions": {}, "capabilities": {}, "rootPath": "/Users/hauleth/Workspace/getkokon/api", "trace": "off"}}]
ndz 14 sty 14:28:27 2018:["<---", 2, "elixir-ls", {"response": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "documentFormattingProvider": true, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "textDocumentSync": 1, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "request": {"method": "initialize", "jsonrpc": "2.0", "id": 1, "params": {"rootUri": "file:///Users/hauleth/Workspace/getkokon/api", "initializationOptions": {}, "capabilities": {}, "rootPath": "/Users/hauleth/Workspace/getkokon/api", "trace": "off"}}}]
ndz 14 sty 14:28:27 2018:["--->", 2, "elixir-ls", {"method": "textDocument/didOpen", "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "version": 1, "languageId": "elixir", "text": "defmodule Kokon.Accounts.User do\n  use Kokon.Schema\n\n  alias Kokon.Accounts.Password\n\n  @moduledoc \"\"\"\n  User account\n  \"\"\"\n\n  schema \"users\" do\n    field :email, :string\n\n    field :password, :string, virtual: true\n    field :password_hash, :string\n\n    field :first_name, :string\n    field :last_name, :string\n\n    field :phone_no, :string\n    field :nickname, :string\n\n    timestamps()\n  end\n\n  @spec changeset(t() | Ecto.Changeset.t(), map()) :: Ecto.Changeset.t()\n  def changeset(struct, params) do\n    \n    struct\n    |> cast(params, ~w[email first_name last_name phone_no nickname password]a)\n    |> validate_format(:email, ~r/@/)\n    |> unique_constraint(:email)\n    |> validate_required(~w[email first_name last_name password]a)\n    |> Password.change()\n  end\nend"}}}]
ndz 14 sty 14:28:27 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "filetype": "elixir", "server_name": "elixir-ls"}, "message": "textDocument/open sent"}}]
ndz 14 sty 14:28:27 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "not dirty"}}]
ndz 14 sty 14:28:27 2018:["<---", 2, "elixir-ls", {"response": {"method": "textDocument/publishDiagnostics", "jsonrpc": "2.0", "params": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "diagnostics": []}}}]
ndz 14 sty 14:28:29 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "server already started"}}]
ndz 14 sty 14:28:29 2018:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "documentFormattingProvider": true, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "textDocumentSync": 1, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "server_name": "elixir-ls"}, "message": "lsp server already initialized"}}]
ndz 14 sty 14:28:29 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "already opened"}}]
ndz 14 sty 14:28:29 2018:["--->", 2, "elixir-ls", {"method": "textDocument/didChange", "params": {"contentChanges": [{"text": "defmodule Kokon.Accounts.User do\n  use Kokon.Schema\n\n  alias Kokon.Accounts.Password\n\n  @moduledoc \"\"\"\n  User account\n  \"\"\"\n\n  schema \"users\" do\n    field :email, :string\n\n    field :password, :string, virtual: true\n    field :password_hash, :string\n\n    field :first_name, :string\n    field :last_name, :string\n\n    field :phone_no, :string\n    field :nickname, :string\n\n    timestamps()\n  end\n\n  @spec changeset(t() | Ecto.Changeset.t(), map()) :: Ecto.Changeset.t()\n  def changeset(struct, params) do\n    Stri\n    struct\n    |> cast(params, ~w[email first_name last_name phone_no nickname password]a)\n    |> validate_format(:email, ~r/@/)\n    |> unique_constraint(:email)\n    |> validate_required(~w[email first_name last_name password]a)\n    |> Password.change()\n  end\nend"}], "textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "version": 2}}}]
ndz 14 sty 14:28:29 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "textDocument/didChange sent"}}]
ndz 14 sty 14:28:29 2018:["--->", 2, "elixir-ls", {"method": "textDocument/completion", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex"}, "position": {"character": 8, "line": 26}}}]
ndz 14 sty 14:28:29 2018:["<---", 2, "elixir-ls", {"response": {"id": 2, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Internal error: an exception was raised:\n    ** (CompileError) /Users/hauleth/Workspace/JakeBecker/elixir-ls/deps/elixir_sense/lib/elixir_sense/core/ast.ex:19: module Kokon.Schema is not loaded and could not be found\n        (elixir) src/elixir_expand.erl:86: :elixir_expand.expand/2\n        (elixir) src/elixir_expand.erl:489: :elixir_expand.expand_block/4\n        (elixir) src/elixir_expand.erl:39: :elixir_expand.expand/2\n        (elixir) src/elixir.erl:265: :elixir.quoted_to_erl/3\n        (elixir) src/elixir.erl:224: :elixir.eval_forms/4\n        (elixir) lib/code.ex:186: Code.eval_string/3\n        (elixir_sense) lib/elixir_sense/core/ast.ex:66: ElixirSense.Core.Ast.add_directive_modules_to_env/3"}}, "request": {"method": "textDocument/completion", "jsonrpc": "2.0", "id": 2, "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex"}, "position": {"character": 8, "line": 26}}}}]
ndz 14 sty 14:28:29 2018:["<---", 2, "elixir-ls", {"response": {"method": "window/logMessage", "jsonrpc": "2.0", "params": {"message": "Process #PID<0.119.0> raised an exception\n** (CompileError) /Users/hauleth/Workspace/JakeBecker/elixir-ls/deps/elixir_sense/lib/elixir_sense/core/ast.ex:19: module Kokon.Schema is not loaded and could not be found\n    (elixir) src/elixir_expand.erl:86: :elixir_expand.expand/2\n    (elixir) src/elixir_expand.erl:489: :elixir_expand.expand_block/4\n    (elixir) src/elixir_expand.erl:39: :elixir_expand.expand/2\n    (elixir) src/elixir.erl:265: :elixir.quoted_to_erl/3\n    (elixir) src/elixir.erl:224: :elixir.eval_forms/4\n    (elixir) lib/code.ex:186: Code.eval_string/3\n    (elixir_sense) lib/elixir_sense/core/ast.ex:66: ElixirSense.Core.Ast.add_directive_modules_to_env/3", "type": 1}}}]
ndz 14 sty 14:28:30 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "server already started"}}]
ndz 14 sty 14:28:30 2018:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "documentFormattingProvider": true, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "textDocumentSync": 1, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "server_name": "elixir-ls"}, "message": "lsp server already initialized"}}]
ndz 14 sty 14:28:30 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "already opened"}}]
ndz 14 sty 14:28:30 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "not dirty"}}]
ndz 14 sty 14:28:30 2018:["--->", 2, "elixir-ls", {"method": "textDocument/completion", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex"}, "position": {"character": 8, "line": 26}}}]
ndz 14 sty 14:28:30 2018:["<---", 2, "elixir-ls", {"response": {"id": 3, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Internal error: an exception was raised:\n    ** (CompileError) /Users/hauleth/Workspace/JakeBecker/elixir-ls/deps/elixir_sense/lib/elixir_sense/core/ast.ex:19: module Kokon.Schema is not loaded and could not be found\n        (elixir) src/elixir_expand.erl:86: :elixir_expand.expand/2\n        (elixir) src/elixir_expand.erl:489: :elixir_expand.expand_block/4\n        (elixir) src/elixir_expand.erl:39: :elixir_expand.expand/2\n        (elixir) src/elixir.erl:265: :elixir.quoted_to_erl/3\n        (elixir) src/elixir.erl:224: :elixir.eval_forms/4\n        (elixir) lib/code.ex:186: Code.eval_string/3\n        (elixir_sense) lib/elixir_sense/core/ast.ex:66: ElixirSense.Core.Ast.add_directive_modules_to_env/3"}}, "request": {"method": "textDocument/completion", "jsonrpc": "2.0", "id": 3, "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex"}, "position": {"character": 8, "line": 26}}}}]
ndz 14 sty 14:28:30 2018:["<---", 2, "elixir-ls", {"response": {"method": "window/logMessage", "jsonrpc": "2.0", "params": {"message": "Process #PID<0.120.0> raised an exception\n** (CompileError) /Users/hauleth/Workspace/JakeBecker/elixir-ls/deps/elixir_sense/lib/elixir_sense/core/ast.ex:19: module Kokon.Schema is not loaded and could not be found\n    (elixir) src/elixir_expand.erl:86: :elixir_expand.expand/2\n    (elixir) src/elixir_expand.erl:489: :elixir_expand.expand_block/4\n    (elixir) src/elixir_expand.erl:39: :elixir_expand.expand/2\n    (elixir) src/elixir.erl:265: :elixir.quoted_to_erl/3\n    (elixir) src/elixir.erl:224: :elixir.eval_forms/4\n    (elixir) lib/code.ex:186: Code.eval_string/3\n    (elixir_sense) lib/elixir_sense/core/ast.ex:66: ElixirSense.Core.Ast.add_directive_modules_to_env/3", "type": 1}}}]
ndz 14 sty 14:28:32 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "server already started"}}]
ndz 14 sty 14:28:32 2018:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "documentFormattingProvider": true, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "textDocumentSync": 1, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "server_name": "elixir-ls"}, "message": "lsp server already initialized"}}]
ndz 14 sty 14:28:32 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "already opened"}}]
ndz 14 sty 14:28:32 2018:["--->", 2, "elixir-ls", {"method": "textDocument/didChange", "params": {"contentChanges": [{"text": "defmodule Kokon.Accounts.User do\n  use Kokon.Schema\n\n  alias Kokon.Accounts.Password\n\n  @moduledoc \"\"\"\n  User account\n  \"\"\"\n\n  schema \"users\" do\n    field :email, :string\n\n    field :password, :string, virtual: true\n    field :password_hash, :string\n\n    field :first_name, :string\n    field :last_name, :string\n\n    field :phone_no, :string\n    field :nickname, :string\n\n    timestamps()\n  end\n\n  @spec changeset(t() | Ecto.Changeset.t(), map()) :: Ecto.Changeset.t()\n  def changeset(struct, params) do\n    St\n    struct\n    |> cast(params, ~w[email first_name last_name phone_no nickname password]a)\n    |> validate_format(:email, ~r/@/)\n    |> unique_constraint(:email)\n    |> validate_required(~w[email first_name last_name password]a)\n    |> Password.change()\n  end\nend"}], "textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "version": 3}}}]
ndz 14 sty 14:28:32 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "textDocument/didChange sent"}}]
ndz 14 sty 14:28:32 2018:["--->", 2, "elixir-ls", {"method": "textDocument/completion", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex"}, "position": {"character": 6, "line": 26}}}]
ndz 14 sty 14:28:32 2018:["<---", 2, "elixir-ls", {"response": {"id": 4, "jsonrpc": "2.0", "error": {"code": -32603, "message": "Internal error: an exception was raised:\n    ** (CompileError) /Users/hauleth/Workspace/JakeBecker/elixir-ls/deps/elixir_sense/lib/elixir_sense/core/ast.ex:19: module Kokon.Schema is not loaded and could not be found\n        (elixir) src/elixir_expand.erl:86: :elixir_expand.expand/2\n        (elixir) src/elixir_expand.erl:489: :elixir_expand.expand_block/4\n        (elixir) src/elixir_expand.erl:39: :elixir_expand.expand/2\n        (elixir) src/elixir.erl:265: :elixir.quoted_to_erl/3\n        (elixir) src/elixir.erl:224: :elixir.eval_forms/4\n        (elixir) lib/code.ex:186: Code.eval_string/3\n        (elixir_sense) lib/elixir_sense/core/ast.ex:66: ElixirSense.Core.Ast.add_directive_modules_to_env/3"}}, "request": {"method": "textDocument/completion", "jsonrpc": "2.0", "id": 4, "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex"}, "position": {"character": 6, "line": 26}}}}]
ndz 14 sty 14:28:32 2018:["<---", 2, "elixir-ls", {"response": {"method": "window/logMessage", "jsonrpc": "2.0", "params": {"message": "Process #PID<0.121.0> raised an exception\n** (CompileError) /Users/hauleth/Workspace/JakeBecker/elixir-ls/deps/elixir_sense/lib/elixir_sense/core/ast.ex:19: module Kokon.Schema is not loaded and could not be found\n    (elixir) src/elixir_expand.erl:86: :elixir_expand.expand/2\n    (elixir) src/elixir_expand.erl:489: :elixir_expand.expand_block/4\n    (elixir) src/elixir_expand.erl:39: :elixir_expand.expand/2\n    (elixir) src/elixir.erl:265: :elixir.quoted_to_erl/3\n    (elixir) src/elixir.erl:224: :elixir.eval_forms/4\n    (elixir) lib/code.ex:186: Code.eval_string/3\n    (elixir_sense) lib/elixir_sense/core/ast.ex:66: ElixirSense.Core.Ast.add_directive_modules_to_env/3", "type": 1}}}]
ndz 14 sty 14:28:33 2018:["s:on_text_document_did_change()", 1]
ndz 14 sty 14:28:33 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "server already started"}}]
ndz 14 sty 14:28:33 2018:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "documentFormattingProvider": true, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "textDocumentSync": 1, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "server_name": "elixir-ls"}, "message": "lsp server already initialized"}}]
ndz 14 sty 14:28:33 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "already opened"}}]
ndz 14 sty 14:28:33 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "not dirty"}}]
ndz 14 sty 14:28:35 2018:["s:on_text_document_did_save()", 1]
ndz 14 sty 14:28:35 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "server already started"}}]
ndz 14 sty 14:28:35 2018:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "documentFormattingProvider": true, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "textDocumentSync": 1, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "server_name": "elixir-ls"}, "message": "lsp server already initialized"}}]
ndz 14 sty 14:28:35 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "already opened"}}]
ndz 14 sty 14:28:35 2018:["--->", 2, "elixir-ls", {"method": "textDocument/didChange", "params": {"contentChanges": [{"text": "defmodule Kokon.Accounts.User do\n  use Kokon.Schema\n\n  alias Kokon.Accounts.Password\n\n  @moduledoc \"\"\"\n  User account\n  \"\"\"\n\n  schema \"users\" do\n    field :email, :string\n\n    field :password, :string, virtual: true\n    field :password_hash, :string\n\n    field :first_name, :string\n    field :last_name, :string\n\n    field :phone_no, :string\n    field :nickname, :string\n\n    timestamps()\n  end\n\n  @spec changeset(t() | Ecto.Changeset.t(), map()) :: Ecto.Changeset.t()\n  def changeset(struct, params) do\n    struct\n    |> cast(params, ~w[email first_name last_name phone_no nickname password]a)\n    |> validate_format(:email, ~r/@/)\n    |> unique_constraint(:email)\n    |> validate_required(~w[email first_name last_name password]a)\n    |> Password.change()\n  end\nend"}], "textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "version": 4}}}]
ndz 14 sty 14:28:35 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "textDocument/didChange sent"}}]
ndz 14 sty 14:28:35 2018:["--->", 2, "elixir-ls", {"method": "textDocument/didSave", "params": {"textDocument": {"uri": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "version": 4}}}]
ndz 14 sty 14:28:35 2018:[{"response": {"data": {"path": "file:///Users/hauleth/Workspace/getkokon/api/apps/kokon/lib/kokon/accounts/user.ex", "__data__": "vim-lsp", "server_name": "elixir-ls"}, "message": "textDocument/didSave sent"}}]
ndz 14 sty 14:28:35 2018:["s:on_text_document_did_close()", 1]
ndz 14 sty 14:28:35 2018:["s:on_exit", 2, "elixir-ls", "exited", 0]
```

**Comment by JakeBecker** [comment]
Based on that log, the client isn't sending the `workspace/didChangeConfiguration` request. It might be possible to make the server perform builds anyway, but really the client should be sending that. Otherwise, there's no way for the user to specify configuration options for the server.

**Comment by JakeBecker** [comment]
Looks like you might need to configure it to send the settings by setting the `g:LanguageClient_loadSettings` option to 1: https://github.com/autozimu/LanguageClient-neovim/pull/179/files#diff-955b9d08c78bce4bdc145172ff4eaf7dR180

**Comment by hauleth** [comment]
It actually sends proper `rootUri` here:

```
ndz 14 sty 14:28:25 2018:["--->", 2, "elixir-ls", {"method": "initialize", "params": {"rootUri": "file:///Users/hauleth/Workspace/getkokon/api", "initializationOptions": {}, "capabilities": {}, "rootPath": "/Users/hauleth/Workspace/getkokon/api", "trace": "off"}}]
ndz 14 sty 14:28:27 2018:["<---", 2, "elixir-ls", {"response": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "documentFormattingProvider": true, "signatureHelpProvider": {"triggerCharacters": ["("]}, "definitionProvider": true, "textDocumentSync": 1, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "request": {"method": "initialize", "jsonrpc": "2.0", "id": 1, "params": {"rootUri": "file:///Users/hauleth/Workspace/getkokon/api", "initializationOptions": {}, "capabilities": {}, "rootPath": "/Users/hauleth/Workspace/getkokon/api", "trace": "off"}}}]
```

Also I am not using LanguageClient-neovim but [vim-lsp](https://github.com/prabirshrestha/vim-lsp).

**Comment by dvcrn** [comment]
I am having the same problem as @hauleth. Also on Mac with no completion for anything except core library. I am using `LanguageClient-neovim` with `g:LanguageClient_loadSettings` but still can't get it to complete for normal project files

**Comment by JakeBecker** [comment]
It's sending the `rootUri`, but there is a separate request needed to send the configuration: https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration .  It seems vim-lsp doesn't send that, which means that configuration settings like `elixirLS.projectDir` can't be sent to the server. The server waits for this configuration notification before it'll do any builds.

**Comment by dvcrn** [comment]
@JakeBecker can you share your configuration for elixir-ls if you're using vim? I am not using `vim-lsp` and can't seem to get it to work for project files either. 

Is there anything I can provide to help with debugging this?

**Comment by myfreeweb** [comment]
With `LanguageClient-neovim` I'm getting "module not loaded" errors whenever I try to do anything (hover, goto def, etc.) in my code:

```
Internal error: an exception was raised:
    ** (CompileError) /usr/home/greg/src/github.com/JakeBecker/elixir-ls/deps/elixir_sense/lib/elixir_sense/core/ast.ex:19: module HTTPotion.Base is not loaded and could not be found

        (elixir) src/elixir_expand.erl:86: :elixir_expand.expand/2
        (elixir) src/elixir_expand.erl:489: :elixir_expand.expand_block/4
        (elixir) src/elixir_expand.erl:39: :elixir_expand.expand/2
        (elixir) src/elixir.erl:265: :elixir.quoted_to_erl/3
        (elixir) src/elixir.erl:224: :elixir.eval_forms/4
        (elixir) lib/code.ex:186: Code.eval_string/3
        (elixir_sense) lib/elixir_sense/core/ast.ex:66: ElixirSense.Core.Ast.add_directive_modules_to_env/3
```

But it works in the `mix.exs`.

**Comment by JakeBecker** [comment]
I've made it do builds with default settings if it doesn't receive `workspace/didChangeConfiguration` within five seconds of initialization. I'll do a release or so in the next week with this change and the autocompletion should work after that.

**Comment by dvcrn** [comment]
Awesome! Thank you, I'll give it a try!

**Comment by will-wow** [comment]
Amazing! The change worked great, I'm getting all the Elixir LS goodness with LanguageClient-neovim now. 🎉
