### ISSUE TITLE
Spawn EACCES Error in VSCode when attempting to Debug

### ISSUE THREAD

**Issue by cburman01** [JakeBecker/elixir-ls#80]
### Environment

* Elixir & Erlang versions (elixir --version): 20.3
* Operating system: RHEL 7.5
* Client (editor or IDE): VSCODE 1.23.1 (node 7.9.0)

### Crash report template
No "ElixirLS" in dropdown.. 

Developer Tools Error: 
spawn EACCESS
 ERR Cannot read property 'kill' of undefined: TypeError: Cannot read property 'kill' of undefined
    at t.stopSession (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2388:146)
    at t.stopServer (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2442:315)
    at t.onDapServerError (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2442:433)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2435:848
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:166:992)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2387:864
    at n.Class.derive._oncancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:152:736)
    at t.startSession (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2387:442)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2436:76
    at n.Class.define.cancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:153:366)
    at t.startSession (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2435:763)
    at t.initServer (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2435:377)
    at t.send (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2436:225)
    at t.disconnect (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2439:887)
    at t.dispose (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2442:723)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:63:281
    at Array.forEach (native)
    at Object.i [as dispose] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:63:249)
    at t.onSessionEnd (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4306:956)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4290:381
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:166:992)
    at t.onDapEvent (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2437:839)
    at t.stopServer (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2442:178)
    at t.onDapServerError (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2442:433)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2435:848
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:166:992)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2387:864
    at n.Class.derive._oncancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:152:736)
    at t.startSession (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2387:442)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2436:76
    at n.Class.define.cancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:153:366)
    at t.startSession (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2435:763)
    at t.initServer (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2435:377)
    at t.send (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2436:225)
    at t.initialize (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2438:77)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4301:261
    at n.Class.define.cancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:153:366)
    at t.doCreateProcess (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4300:526)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4299:682
    at n.Class.define.cancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:153:366)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4299:516
    at n.Class.derive._creator.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:153:366)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4298:954
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:146:807)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:150:85)
    at n.Class.derive._creator._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:151:896)
    at n.Class.derive._creator._completed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:151:337)
    at <anonymous>
workbench.main.js:1328   ERR Cannot read property 'kill' of undefined: TypeError: Cannot read property 'kill' of undefined
    at t.stopSession (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2388:146)
    at t.stopServer (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2442:315)
    at t.onDapServerError (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2442:433)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2435:848
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:166:992)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2387:864
    at n.Class.derive._oncancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:152:736)
    at t.startSession (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2387:442)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2436:76
    at n.Class.define.cancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:153:366)
    at t.startSession (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2435:763)
    at t.initServer (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2435:377)
    at t.send (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2436:225)
    at t.initialize (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2438:77)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4301:261
    at n.Class.define.cancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:153:366)
    at t.doCreateProcess (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4300:526)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4299:682
    at n.Class.define.cancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:153:366)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4299:516
    at n.Class.derive._creator.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:153:366)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4298:954
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:146:807)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:150:85)
    at n.Class.derive._creator._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:151:896)
    at n.Class.derive._creator._completed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:151:337)
    at <anonymous>

**Comment by cburman01** [comment]
After some digging, it was the permissions of the sh scripts at this location: 
`.vscode/extensions/JakeBecker.elixir-ls-0.2.19/elixir-ls-release`

This was the fix in that folder: 
`chmod +x *.sh`

Thanks.

**Comment by JakeBecker** [comment]
I wonder why... When I install it in macOS, the permissions are correct. I wonder if it's some kind of security thing in RHEL. Glad you fixed it!

**Comment by pragdave** [comment]
Ah, that chmod fixed it for me, too. (Ubuntu 18.04)

**Comment by wende** [comment]
Had the same problem on MacOS. Chmod fixed it

**Comment by silverdr** [comment]
FWIW - three years later the magical `chmod` still fixes the "couldn't start client ElixirLS" with all of its repercussions
