### ISSUE TITLE
ElixirLS in VS Code crashing on 0.2.20

### ISSUE THREAD

**Issue by shdblowers** [JakeBecker/elixir-ls#92]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6.2
* Operating system:  Mac OS
* Client (editor or IDE): VS Code
* Elixir LS version: 0.2.20

### Crash report template

This started this morning, when I launch VS Code, the extension crashes with no output.

<img width="1066" alt="screen shot 2018-07-11 at 12 46 42 pm" src="https://user-images.githubusercontent.com/11884841/42569505-a059ee36-8508-11e8-9366-475c9e53a422.png">

**Comment by shdblowers** [comment]
I was in wrong section on output screen, here is last message before crash:

```
[Error - 12:46:23] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-jsonrpc/lib/messageReader.js:135:27)
	at Socket.<anonymous> (/Users/steven/.vscode/extensions/jakebecker.elixir-ls-0.2.20/node_modules/vscode-jsonrpc/lib/messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by shdblowers** [comment]
There is also this which might be helpful

```
[Error - 13:10:41] Task #PID<0.2800.0> started from #PID<0.2648.0> terminating
** (ArgumentError) argument error
    :erlang.++(<<70, 79, 82, 49, 0, 0, 6, 212, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 1, 18, 0, 0, 0, 29, 3, 106, 115, 120, 6, 101, 110, 99, 111, 100, 101, 11, 106, 115, 120, 95, 116, 111, 95, 106, 115, 111, 110, 7, 116, 111, ...>>, '\n')
    dialyzer_utils.erl:120: :dialyzer_utils.get_core_from_beam/2
    (language_server) lib/language_server/dialyzer.ex:361: ElixirLS.LanguageServer.Dialyzer.module_md5/1
    (language_server) lib/language_server/dialyzer.ex:214: anonymous fn/1 in ElixirLS.LanguageServer.Dialyzer.update_stale/4
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<8.107201030/1 in ElixirLS.LanguageServer.Dialyzer.update_stale/4>, [".elixir_ls/build/test/lib/jsx/ebin/jsx.beam"]]
```

**Comment by shdblowers** [comment]
It works on other projects I have, just not on this specific one I am developing at work.

**Comment by JakeBecker** [comment]
This is being caused by a problem with the Dialyzer integration. I've fixed it in master, and I'll release an update pretty soon. In the meantime, you should be able to set `dialyzerEnabled: false` in your `settings.json` to avoid it.

**Comment by shdblowers** [comment]
thanks very much @JakeBecker

**Comment by shdblowers** [comment]
I've updated to `0.2.21` and everything is 💚 

Thanks again for your work on fixing this and the whole thing in general 😄
